# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ArZMa8cCd47SUnqSruonYaYv7ZiZSJug
"""

##pip install flask pandas

import pandas as pd

# Load your dataset
data = pd.read_excel("bot.xlsx")

# Assuming the columns in your Excel sheet are named "description" and "link"
descriptions = data["HC Name"]
links = data["Link"]

from flask import Flask, jsonify, request

app = Flask(__name__)

# Function to get the link based on description
def get_link(description):
    # Perform any necessary preprocessing or string matching here
    # For simplicity, we'll use exact matching in this example
    index = descriptions[descriptions == description].index[0]
    return links[index]

# API endpoint to get the link for a given description
@app.route("/get_link", methods=["POST"])
def get_link_endpoint():
    data = request.get_json()
    description = data["description"]

    link = get_link(description)
    if link:
        response = {"link": link}
    else:
        response = {"message": "Description not found."}

    return jsonify(response)

if __name__ == "__main__":
    app.run(8080)
